log_dir: './outputs/H36M/logs/'
checkpoint_dir: './outputs/H36M/checkpoints/'
pred_dir: './outputs/H36M/plots/prediction/'
CM_dir: './outputs/H36M/plots/Confusion_Matrix/'

TASK: 'regression'#'classification' 'regression' 'MTL' 'MTL-Emb'
STEPS: 200
BATCH_SIZE: 32
HISTORY: None
KERNEL_INIT: "uniform"
THREADS: 12
LR: [ 5e-3, 1e-3,1e-4, 5e-4, 5e-5, 1e-5]
NUMBER_OF_CLASSES: 17
n_nodes: [50, 50, 50, 50] #EDTCN hidden layers size
PATIENCE: 15 # for early stopping
loss_reg: MSE #SmoothL1 # MSE # L1 # MSEL1 # MSESmoothL1
